# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0284_admissioncondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionConditionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('admission_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AdmissionCondition')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionConditionSubLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.TextField(max_length=32)),
                ('condition', models.TextField(max_length=32)),
                ('access', models.TextField(max_length=32)),
                ('remarques', models.TextField(max_length=32)),
                ('text_libre', models.TextField()),
                ('admission_condition_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AdmissionConditionLine')),
            ],
        ),
    ]
