# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0285_admissionconditionline_admissionconditionsubline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncondition',
            name='education_group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType', unique=True),
        ),
    ]
