# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0286_auto_20180608_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncondition',
            name='education_group_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear', unique=True),
        ),
        migrations.AlterField(
            model_name='admissioncondition',
            name='education_group_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType', unique=True),
        ),
    ]
