# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0287_auto_20180613_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionConditionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No description', max_length=64)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.AdmissionConditionSection')),
            ],
        ),
    ]
