# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0288_admissionconditionsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionconditionsection',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.AdmissionConditionSection'),
        ),
    ]
