# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0289_auto_20180613_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionconditionsection',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionconditionsection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.AdmissionConditionSection'),
        ),
    ]
