# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0290_auto_20180613_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionconditionline',
            name='title',
        ),
        migrations.RemoveField(
            model_name='admissionconditionsubline',
            name='text_libre',
        ),
        migrations.AddField(
            model_name='admissionconditionline',
            name='admission_condition_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.AdmissionConditionSection'),
        ),
        migrations.AddField(
            model_name='admissionconditionline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
