# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0291_auto_20180613_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncondition',
            name='description',
        ),
    ]
