# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0293_auto_20180618_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncondition',
            name='education_group_type',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='education_group_year',
        ),
        migrations.RemoveField(
            model_name='admissionconditionline',
            name='admission_condition',
        ),
        migrations.RemoveField(
            model_name='admissionconditionline',
            name='admission_condition_section',
        ),
        migrations.RemoveField(
            model_name='admissionconditionsection',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='admissionconditionsubline',
            name='admission_condition_line',
        ),
        migrations.DeleteModel(
            name='AdmissionCondition',
        ),
        migrations.DeleteModel(
            name='AdmissionConditionLine',
        ),
        migrations.DeleteModel(
            name='AdmissionConditionSection',
        ),
        migrations.DeleteModel(
            name='AdmissionConditionSubLine',
        ),
    ]
