# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0294_auto_20180620_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_group_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionConditionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('diploma', models.TextField()),
                ('conditions', models.TextField()),
                ('access', models.TextField()),
                ('remarks', models.TextField()),
                ('admission_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AdmissionCondition')),
            ],
        ),
    ]
