# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0295_auto_20180627_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCondition',
            fields=[
                ('education_group_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.EducationGroupYear')),
                ('text_bachelor', models.TextField(default='')),
                ('text_alert_message', models.TextField(default='')),
                ('text_standard', models.TextField(null=True)),
                ('text_free', models.TextField(default='')),
                ('text_university_bachelors', models.TextField(default='')),
                ('text_non_university_bachelors', models.TextField(default='')),
                ('text_holders_second_university_degree', models.TextField(default='')),
                ('text_holders_non_university_second_degree', models.TextField(default='')),
                ('text_adults_taking_up_university_training', models.TextField(default='')),
                ('text_personalized_access', models.TextField(default='')),
                ('text_admission_enrollment_procedures', models.TextField(default='')),
                ('text_bachelor_en', models.TextField(default='')),
                ('text_alert_message_en', models.TextField(default='')),
                ('text_standard_en', models.TextField(null=True)),
                ('text_free_en', models.TextField(default='')),
                ('text_university_bachelors_en', models.TextField(default='')),
                ('text_non_university_bachelors_en', models.TextField(default='')),
                ('text_holders_second_university_degree_en', models.TextField(default='')),
                ('text_holders_non_university_second_degree_en', models.TextField(default='')),
                ('text_adults_taking_up_university_training_en', models.TextField(default='')),
                ('text_personalized_access_en', models.TextField(default='')),
                ('text_admission_enrollment_procedures_en', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionConditionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('diploma', models.TextField(null=True)),
                ('conditions', models.TextField(null=True)),
                ('access', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('diploma_en', models.TextField(null=True)),
                ('conditions_en', models.TextField(null=True)),
                ('access_en', models.TextField(null=True)),
                ('remarks_en', models.TextField(null=True)),
                ('admission_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AdmissionCondition')),
            ],
        ),
    ]
