# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0295_admissioncondition_admissionconditionline'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncondition',
            name='text_adult',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_bachelor_university',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_custom_access',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_diploma_second_cycle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_first_bachelor_non_university',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_first_group',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_first_procedure',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_second_bachelor_non_university',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_second_group',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_second_procedure',
            field=models.TextField(default=''),
        ),
    ]
