# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0296_auto_20180620_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncondition',
            name='text_bachelor',
            field=models.TextField(default=''),
        ),
    ]
