# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0297_admissioncondition_text_bachelor'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncondition',
            name='text_diploma_second_cycle_non_university',
            field=models.TextField(default=''),
        ),
    ]
