# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0298_admissioncondition_text_diploma_second_cycle_non_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncondition',
            name='id',
        ),
        migrations.AlterField(
            model_name='admissioncondition',
            name='education_group_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.EducationGroupYear'),
        ),
    ]
