# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0299_auto_20180621_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncondition',
            name='text_adult_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_bachelor_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_bachelor_university_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_custom_access_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_diploma_second_cycle_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_diploma_second_cycle_non_university_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_first_bachelor_non_university_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_first_group_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_first_procedure_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_second_bachelor_non_university_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_second_group_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_second_procedure_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissionconditionline',
            name='access_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissionconditionline',
            name='conditions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissionconditionline',
            name='diploma_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissionconditionline',
            name='remarks_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admissionconditionline',
            name='access',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admissionconditionline',
            name='conditions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admissionconditionline',
            name='diploma',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admissionconditionline',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
