# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-22 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0300_auto_20180621_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_first_group',
            new_name='text_alert_message',
        ),
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_first_group_en',
            new_name='text_alert_message_en',
        ),
    ]
