# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0301_auto_20180622_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncondition',
            name='text_standard',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_standard_en',
            field=models.TextField(null=True),
        ),
    ]
