# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0302_auto_20180625_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_second_group',
            new_name='text_free',
        ),
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_second_group_en',
            new_name='text_free_en',
        ),
    ]
