# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0305_auto_20180625_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_second_bachelor_non_university',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_second_bachelor_non_university_en',
        ),
    ]
