# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0306_auto_20180625_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_diploma_second_cycle',
            new_name='text_holders_second_university_degree',
        ),
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_diploma_second_cycle_en',
            new_name='text_holders_second_university_degree_en',
        ),
    ]
