# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0308_auto_20180625_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_adult',
            new_name='text_adults_taking_up_university_training',
        ),
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_adult_en',
            new_name='text_adults_taking_up_university_training_en',
        ),
    ]
