# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0310_auto_20180625_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_first_procedure',
            new_name='text_admission_enrollment_procedures',
        ),
        migrations.RenameField(
            model_name='admissioncondition',
            old_name='text_first_procedure_en',
            new_name='text_admission_enrollment_procedures_en',
        ),
    ]
