# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0311_auto_20180625_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_second_procedure',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_second_procedure_en',
        ),
    ]
